# Generated by Django 4.2.10 on 2024-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0002_alter_notification_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
