# Generated by Django 4.2.10 on 2024-04-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0003_alter_notification_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_count',
            field=models.IntegerField(default=0),
        ),
    ]
