# Generated by Django 4.2.10 on 2024-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_transferrequest_transaction_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
