# Generated by Django 4.2.10 on 2024-04-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_alter_transaction_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='main_currency',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile.jpg', upload_to='profile'),
        ),
    ]
